### ISSUE TITLE
[Enhancement] Ways to configure Filters are confusing.

### ISSUE THREAD

**Issue by 1sixth** [tatsuz0u/EhPanda#46]
## Is your feature request related to a problem? Please describe.

Currently, there are two ways to configure Filters in EhPanda:

1. Setting --> Account --> Account configuration
2. Setting --> General --> Filters

According to my test, it seems that:

1. Filters configured in the first way only filters gallerys showing up in Frontpage, Popular and Watched.
2. Filters configured in the second way only filters gallerys showing up in search results.

This is never mentioned in the app or any online documentation, and it's kind of frustrating.

## Describe the solution you'd like

Remove the second way and provide a new way to apply Filters and other Advanced Options when searching. This is exactly what the E-Hentai website is doing.

## Describe alternatives you've considered

1. Explain in the app about how these settings applies to certain circumstances, so users won't get confused.
2. Do nothing, let users find it out themselves.

## Additional context

None.

**Comment by tatsuz0u** [comment]
Yes, putting Filters setting there is quite confusing.
In previous versions, the entry button of Filters setting positioned inside the search bar, it was much easier to infer its usage.
But since I replaced the search bar with the brand new `.searchable()`, it seems impossible to put a button inside, I thought about using a keyboard toolbar item instead, but the toolbar won't show up if the keyboard is summoned by `.searchable()`, so I have to put the entry inside the general setting temporarily.
About the "account configuration", it actually means E-Hentai settings, it should not be regarded as a Filters setting.

Thanks for your advice, I appreciate it.

**Comment by 1sixth** [comment]
> About the "account configuration", it actually means E-Hentai settings, it should not be regarded as a Filters setting.

I don't think that's correct. Because you can configure what categories to show in E-Hentai settings:

![screenshot](https://user-images.githubusercontent.com/67363572/131846669-07606ff0-ab9b-4ba9-9847-0f67df2fee8c.png)

For example, if we choose not to show *Misc* in E-Hentai settings, then those gallerys categorized as *Misc* won't be shown on the front page **and in searches** by default. This is not what EhPanda behaves currently. Filter changes made in E-Hentai settings don't apply in searches. If users want the same experience as the E-Hentai website in EhPanda, they have to manually configure EhPanda's own Filter to match the E-Hentai website's settings.

> But since I replaced the search bar with the brand new .searchable(), it seems impossible to put a button inside, I thought about using a keyboard toolbar item instead, but the toolbar won't show up if the keyboard is summoned by .searchable(), so I have to put the entry inside the general setting temporarily.

It's just a little glitch, though. I'm perfectly fine with the temporary situation. I really appreciate your effort in making EhPanda a better piece of software.

**Comment by tatsuz0u** [comment]
Done. 489dbbd2fd2ed284671a3cb892efe26ce5e5a74b
